#!/usr/bin/env bash

#Check if arg is not provided
if [ -z "$1"]; then
    echo "Arg not provided"
else
    export VPC_ID="$1"
fi

if [ -z "$2"]; then
    echo "Arg not provided"
else
    export IGW_ID="$2"
fi

if [ -z "$3"]; then
    echo "Arg not provided"
else
    export SUBNETID="$3"
fi

if [ -z "$4"]; then
    echo "Arg not provided"
else
    export RT_ID="$4"
fi

# detatch IGW

aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete IGW

# disassociate

aws ec2 disassociate-route-table --association-id 

# delete subnet

aws ec2 delete-subnet --subnet-id $SUBNETID

# delete route table

aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc

aws ec2 delete-vpc --vpc-id $VPC_ID
