#!/usr/bin/env bash

echo "== deploy global accelerator instance"

STACK_NAME="aws-global-acc-basic"

aws cloudformation deploy --template-file template.yaml --capabilities CAPABILITY_NAMED_IAM --no-execute-changeset --region us-east-1 --stack-name $STACK_NAME