AWSTemplateFormatVersion: "2010-09-09"
Description: Launch simple EC2 for testing VPCs
Parameters:
  VpcID: 
    Type: String
    Default: vpc-0682d8aa64d880a7e
  SubnetId:
    Type: String
    Default: subnet-0e9d1acc40a5aa832
Resources: 
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t3.micro"
      ImageId: "ami-01edba92f9036f76e"
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          AssociatePublicIpAddress: true
          GroupSet:
            - !GetAtt SG.GroupId
          DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Hello smeh from Apache on Amazon Linux</h1></body></html>" > /var/www/html/index.html
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  